### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'query_universal_transfer_history'

### ISSUE THREAD

**Issue by jontstaz** [EtWnn/BinanceWatch#26]
First of all, nice project. Just noticed a couple of bugs.

It seems to fail when trying to fetch transfer history. It also often fails due to reaching API limits so perhaps the next update could include throttling?

Cheers,

**Comment by EtWnn** [comment]
Hi jontstaz,

Thanks for trying out my project and for the feedback!

I am working on API limits, it will be integrated during this week

For the transfer history, it works fine on my end so could you give me some details:
- Your Binance-Watch version
- Your python-binance version
- The full text of the error and the code you tried to execute

That would help me to locate the error

**Comment by EtWnn** [comment]
API limits have been integrated in the develop branch with the PR #28 
It will be published in the release 0.1.2 later this week

**Comment by EtWnn** [comment]
I also added a version requirement for python-binance which should fix your AttributeError

**Comment by jontstaz** [comment]
Thanks mate. Upgraded to v0.1.2. Still getting rate limited. Doe
```
"...python3.8/site-packages/BinanceWatch/BinanceManager.py", line 792, in _call_binance_client
    raise RuntimeError(f"The API rate limits has been breached {retry_count} times")
RuntimeError: The API rate limits has been breached 3 times
```

Note: I have a lot of trade history to parse so maybe the limit is still too high over extended periods? Will take a look soon myself. I know with ccxt you can set a rate_limit boolean to true and it throttles requests for you.

**Comment by EtWnn** [comment]
Thanks for the feedback.

The RuntimeError you got is a fail safe I put in case you got 3 times in a **row** an API rate limit error to prevent a ban, even so the library is supposed to wait the indicated time by Binance after each API Rate limit error.

It may be du to my connection, but I have a hard time getting API rate error to test this so I will gladly take every clue you can give me to fix the issue.

If you are using jupyter notebook, could you add this in the first cell:
```
import logging
from BinanceWatch.utils.LoggerGenerator import LoggerGenerator
LoggerGenerator.set_global_log_level(logging.INFO)
```
This will print out useful messages to know what's going on inside.
Could you then run your code again in lower cells and paste here the logs that are printed out?

**Comment by EtWnn** [comment]
After a bit of search, it seems that the field 'retry-after' in the response header is always 0, when according to the [documentation](https://binance-docs.github.io/apidocs/spot/en/#limits) it should be this:

> A Retry-After header is sent with a 418 or 429 responses and will give the number of seconds required to wait, in the case of a 429, to prevent a ban, or, in the case of a 418, until the ban is over.

It looks like I will have to handle the throttling from the library directly, I will keep you updated

**Comment by EtWnn** [comment]
The PR #35 is a quick fix for this but it should work, you can pull the latest dev version with
`pip install git+https://github.com/EtWnn/BinanceWatch.git@develop`

**Comment by jontstaz** [comment]
Thanks mate. I pulled the update from the develop branch and I got what looks to be an sqlite parsing error. It did make it much further through the process than it has before though. Will take a look and see what I can do.

![image](https://user-images.githubusercontent.com/6379873/113534679-c5faea80-9614-11eb-9fc9-e2dce847683d.png)

**Comment by jontstaz** [comment]
Fixed https://github.com/EtWnn/BinanceWatch/pull/36

**Comment by EtWnn** [comment]
Glad to hear that the rate limit error seemed to be fixed. Thanks for the feedback!

For the IntegrityError, could you open a new issue? This one start to go off tracks (the initial error was a python-binance version error, which has been fixed)
